-----------------------------------------------------------------------------------------------------------------------
-------------------------------DONT EDIT UNLESS YOU KNOW WHAT YOUR DOING-----------------------------------------------
-----------------------------------------------------------------------------------------------------------------------
RegisterCommand("loadout", function(source, args)
	args = table.concat(args, " ")
	username = GetPlayerName(PlayerId())
	if args == "bcso" then
		TriggerServerEvent("loadout", username)
		giveWeapon("weapon_carbinerifle")
		giveWeapon("weapon_pumpshotgun")
		giveWeapon("weapon_combatpistol")
		giveWeapon("weapon_stungun")
		giveWeapon("weapon_flashlight")
		giveWeapon("weapon_flare")
		giveWeapon("weapon_petrolcan")
		giveWeapon("weapon_nightstick")
		weaponComponent("weapon_combatpistol", "COMPONENT_AT_PI_FLSH")
		weaponComponent("weapon_pumpshotgun", "COMPONENT_AT_AR_FLSH")
		weaponComponent("weapon_carbinerifle", "COMPONENT_AT_SCOPE_MEDIUM")
		weaponComponent("weapon_carbinerifle", "COMPONENT_AT_AR_FLSH")
		weaponComponent("weapon_carbinerifle", "COMPONENT_AT_AR_AFGRIP")
	elseif args == "sahp" then
		TriggerServerEvent("loadout1", username)
		giveWeapon("weapon_carbinerifle")
		giveWeapon("weapon_pumpshotgun")
		giveWeapon("weapon_combatpistol")
		giveWeapon("weapon_stungun")
		giveWeapon("weapon_flashlight")
		giveWeapon("weapon_flare")
		giveWeapon("weapon_petrolcan")
		giveWeapon("weapon_nightstick")
		weaponComponent("weapon_combatpistol", "COMPONENT_AT_PI_FLSH")
		weaponComponent("weapon_pumpshotgun", "COMPONENT_AT_AR_FLSH")
		weaponComponent("weapon_carbinerifle", "COMPONENT_AT_SCOPE_MEDIUM")
		weaponComponent("weapon_carbinerifle", "COMPONENT_AT_AR_FLSH")
		weaponComponent("weapon_carbinerifle", "COMPONENT_AT_AR_AFGRIP")
	elseif args == "lspd" then
		TriggerServerEvent("loadout1", username)
		giveWeapon("weapon_carbinerifle")
		giveWeapon("weapon_pumpshotgun")
		giveWeapon("weapon_combatpistol")
		giveWeapon("weapon_stungun")
		giveWeapon("weapon_flashlight")
		giveWeapon("weapon_flare")
		giveWeapon("weapon_petrolcan")
		giveWeapon("weapon_nightstick")
		weaponComponent("weapon_combatpistol", "COMPONENT_AT_PI_FLSH")
		weaponComponent("weapon_pumpshotgun", "COMPONENT_AT_AR_FLSH")
		weaponComponent("weapon_carbinerifle", "COMPONENT_AT_SCOPE_MEDIUM")
		weaponComponent("weapon_carbinerifle", "COMPONENT_AT_AR_FLSH")
		weaponComponent("weapon_carbinerifle", "COMPONENT_AT_AR_AFGRIP")
	elseif args == "swat" then
		TriggerServerEvent("loadout1", username)
		giveWeapon("weapon_carbinerifle")
		giveWeapon("weapon_pumpshotgun")
		giveWeapon("weapon_combatpistol")
		giveWeapon("weapon_stungun")
		giveWeapon("weapon_flashlight")
		giveWeapon("weapon_heavysniper_mk2")
		weaponComponent("weapon_combatpistol", "COMPONENT_AT_PI_FLSH")
		weaponComponent("weapon_heavysniper_mk2", "COMPONENT_MARKSMANRIFLE_MK2_CLIP_FMJ")
		weaponComponent("weapon_heavysniper_mk2", "COMPONENT_AT_MUZZLE_02")
		weaponComponent("weapon_heavysniper_mk2", "	COMPONENT_AT_MRFL_BARREL_02")
		weaponComponent("weapon_pumpshotgun", "COMPONENT_AT_AR_FLSH")
		weaponComponent("weapon_carbinerifle", "COMPONENT_AT_SCOPE_MEDIUM")
		weaponComponent("weapon_carbinerifle", "COMPONENT_AT_AR_FLSH")
		weaponComponent("weapon_carbinerifle", "COMPONENT_AT_AR_AFGRIP")
	end
end)
